import { describe, expect, test } from "bun:test";
import { ProcessCodexQueueClient } from "../src/desktop/codex-queue-client.ts";
import { routeThreadReply } from "../src/telegram/thread-reply-router.ts";
import { StateDb } from "../src/state/db.ts";
import { DesktopMessageStore } from "../src/state/desktop-message-store.ts";

function linkedStore(): { state: StateDb; store: DesktopMessageStore } {
  const state = new StateDb(":memory:");
  const store = new DesktopMessageStore(state);
  store.link({ chatId: "42", messageId: 99, threadId: "thread-a", turnId: "turn-a", eventKind: "completed", eventFingerprint: "event-a" });
  return { state, store };
}

describe("routeThreadReply", () => {
  test("requires a reply to a mapped Sea-Bridge message", async () => {
    const { state, store } = linkedStore();
    const queueClient = new ProcessCodexQueueClient("/codex", async () => ({ exitCode: 0, signal: null, stderr: "" }));

    await expect(routeThreadReply(10, { message_id: 10, chat: { id: 42, type: "private" }, text: "continue" }, store, queueClient)).resolves.toEqual({ status: "missing_reply" });
    state.close();
  });

  test("delivers a mapped reply once to its original thread", async () => {
    const { state, store } = linkedStore();
    const calls: string[][] = [];
    const queueClient = new ProcessCodexQueueClient("/codex", async (_command, args) => {
      calls.push(args);
      return { exitCode: 0, signal: null, stderr: "" };
    });
    const message = {
      message_id: 10,
      chat: { id: 42, type: "private" },
      text: "continue",
      reply_to_message: { message_id: 99, chat: { id: 42, type: "private" } },
    };

    await expect(routeThreadReply(10, message, store, queueClient)).resolves.toEqual({ status: "delivered", threadId: "thread-a" });
    await expect(routeThreadReply(10, message, store, queueClient)).resolves.toEqual({ status: "duplicate" });
    expect(calls).toEqual([["queue", "--thread", "thread-a", "--message", "[Telegram reply]\ncontinue"]]);
    expect(store.getDelivery(10)?.status).toBe("delivered");
    state.close();
  });

  test("delivers reply to a prompt message generated by quick reply button", async () => {
    const { state, store } = linkedStore();
    store.link({
      chatId: "42",
      messageId: 100,
      threadId: "thread-a",
      turnId: null,
      eventKind: "reply_prompt",
      eventFingerprint: "prompt-fingerprint",
    });
    const calls: string[][] = [];
    const queueClient = new ProcessCodexQueueClient("/codex", async (_command, args) => {
      calls.push(args);
      return { exitCode: 0, signal: null, stderr: "" };
    });
    const message = {
      message_id: 101,
      chat: { id: 42, type: "private" },
      text: "reply via prompt",
      reply_to_message: { message_id: 100, chat: { id: 42, type: "private" } },
    };

    await expect(routeThreadReply(11, message, store, queueClient)).resolves.toEqual({ status: "delivered", threadId: "thread-a" });
    expect(calls).toEqual([["queue", "--thread", "thread-a", "--message", "[Telegram reply]\nreply via prompt"]]);
    expect(store.getDelivery(11)?.status).toBe("delivered");
    state.close();
  });
});
